config/routes.rb
DmChallenge::Application.routes.draw do
  root "welcome#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :challenges

  resources :users do
    resources :activities
  end

  get "/dashboard" => "dashboard#index"
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user

  validates :distance, presence: true, :numericality => { greater_than: 0 }
  validates :date, presence: true

  def self.total_distance_between period
    between(period).sum(:distance)
  end

  def self.total_ascent_between period
    between(period).sum(:ascent)
  end

  def self.total_achievements_between period
    between(period).sum(:achievements)
  end

  def self.between period
    where(date: period.start..period.finish)
  end
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  has_many :users

  def target
    users.sum(:commitment)
  end

  def daily_average
    (target / total_days).to_i
  end

  def total_days
    (end_date - start_date + 1).to_i
  end

  def target_needed_to_date
    (start_date < Time.current.to_date) ? daily_average * current_day_count : 0
  end

  def current_day_count
    (Time.current.to_date - start_date + 1).to_i
  end

  def days_left
    (end_date - Time.current.to_date).to_i
  end

  def accumulated_total
    users.inject(0) { |result, user| result + user.total_distance_for(period) }
  end

  def deficit
    target_needed_to_date - accumulated_total
  end

  def user_with_highest_kilometers
    users.highest_kilometers_within_period period
  end

  def user_with_highest_ascent
    users.highest_ascent_within_period period
  end

  def user_with_highest_achievements
    users.highest_achievements_within_period period
  end

  def highest_kilometers? user
    user == user_with_highest_kilometers
  end

  def highest_ascent? user
    user == user_with_highest_ascent
  end

  def highest_achievements? user
    user == user_with_highest_achievements
  end

  def period
    # TODO - change to start_date..end_date
    OpenStruct.new(start: start_date, finish: end_date)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :challenge
  has_many :activities

  #validates :commitment, presence: true, :numericality => { greater_than: 0 }
  validates :name, presence: true

  def daily_average
    (commitment / challenge.total_days).to_i
  end

  def daily_average_needed_to_complete_challenge
    ((commitment - total_distance_for(challenge.period)) / (challenge.days_left + 1))
  end

  def total_kilometers_needed_to_date
    (challenge.start_date < Time.current.to_date) ? daily_average * (Time.current.to_date - challenge.start_date + 1).to_i : 0
  end

  def total_distance_for period
    activities.total_distance_between period
  end

  def total_ascent_for period
    activities.total_ascent_between period
  end

  def total_achievements_for period
    activities.total_achievements_between period
  end

  def activities_for period
    activities.between(period)
  end

  def percent_completed
    commitment ? ((total_distance_for(challenge.period).to_f / commitment) * 100).to_i : 0
  end

  def preferred_name
    nickname.presence || name
  end

  def highest_kilometers?
    challenge.user_with_highest_kilometers == self
  end

  def self.highest_kilometers_within_period period
    all.max { |a, b| a.activities.total_distance_between(period)\
      <=> b.activities.total_distance_between(period) }
  end

  def self.highest_ascent_within_period period
    all.max { |a, b| a.activities.total_ascent_between(period)\
      <=> b.activities.total_ascent_between(period) }
  end

  def self.highest_achievements_within_period period
    all.max { |a, b| a.activities.total_achievements_between(period)\
      <=> b.activities.total_achievements_between(period) }
  end

  def self.from_omniauth auth
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.challenge = Challenge.last
      #user.commitment = 500
      user.save!
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authorize

  def index
    @challenge  = Challenge.last
    @user       = User.find(params[:user_id])
    @activities = @user.activities_for(@challenge.period)
  end

  def new
    @user     = User.find(params[:user_id])
    @activity = @user.activities.new
    @activity.date ||= DateTime.current.strftime("%Y-%m-%d")
  end

  def create
    @user     = User.find(params[:user_id])
    @activity = @user.activities.new(activity_params)
    if @activity.save
      redirect_to user_activities_path(@user),\
        notice: "Activity successfully created!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @activity = @user.activities.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @activity = Activity.find(params[:id])
    if @activity.update(activity_params)
      redirect_to user_activities_path(@user),\
        notice: "Activity successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @activity = Activity.find(params[:id])
    @activity.destroy!
    redirect_to user_activities_path(@user),\
      alert: "Activity successfully deleted!"
  end

    private

    def activity_params
      params.require(:activity).permit(:date, :distance, :ascent, :achievements)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to root_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authorize, only: [:index]

  def index
    @challenge = Challenge.last
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to dashboard_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def challenge_countdown
    if Time.current < @challenge.start_date
      content_tag("strong", distance_of_time_in_words(Time.now-1.days,\
        @challenge.start_date) + " to start!")
    else
      content_tag("strong", distance_of_time_in_words(@challenge.end_date,\
        Time.current-1.days) + " left!")
    end
  end

  def style_deficit
    deficit_warning_class unless @challenge.deficit <= 0
  end

  def style_challenge
    @challenge.deficit <= 0 ? "btn-success" : "btn-primary"
  end

  private

  def deficit_warning_class
    @challenge.deficit <= 100 ? "btn-warning" : "btn-danger"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.erb
<%= form_for([@user, @activity]) do |f| %>
  <%=  render "shared/errors", object: @activity %>
  <fieldset>
    <div class="row">
      <div class="span3 required">
        <%= f.label :date %>
        <%= f.text_field :date, autofocus: true%>
      </div>
    </div>
    <div class="row">
      <div class="span3">
        <small>(date format: YYYY-MM-DD)</small>
      </div>
    </div>
    <div class="row">
      <div class="span3 required">
        <%= f.label :distance %>
        <%= f.text_field :distance %>
      </div>
    </div>
    <div class="row">
      <div class="span3 required">
        <%= f.label :ascent %>
        <%= f.text_field :ascent%>
      </div>
    </div>
    <div class="row">
      <div class="span3 required">
        <%= f.label :achievements %>
        <%= f.text_field :achievements%>
      </div>
    </div>
    <div class="row">
      <div class="span3 required">
        <%= f.submit %>
        <%= link_to "Cancel", user_activities_path(@user), class: 'button' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/activities/edit.html.erb
<header id="content-header">
  <h1>Edit Activity</h1>
</header>

<%= render 'form' %>

app/views/activities/index.html.erb
<h1><%= @user.preferred_name %>'s activities</h1>
<small>
  Commitment <%= @user.commitment %><br>
  Current total <%= @user.total_distance_for @challenge.period %><br>
  Needed to be on track <%= @user.total_kilometers_needed_to_date %><br>
  Daily avg needed to finish challenge <%= @user.daily_average_needed_to_complete_challenge %><br>
</small><br>
<%= link_to( image_tag('add.png'), new_user_activity_path(@user)) %><br><br>
<% if @activities.count == 0 %>
<br><br>
There are currently no activities!
<% else %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Date</th>
      <th>kms</th>
      <th>m</th>
      <th>#</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @activities.order('date desc').each do |activity| %>
      <tr>
        <td><%= activity.date %></td>
        <td><%= activity.distance %></td>
        <td><%= activity.ascent %></td>
        <td><%= activity.achievements %></td>
        <td><%= link_to( image_tag('modify.png'), edit_user_activity_path(@user, activity)) %>
            <%= link_to( image_tag('delete.png'), user_activity_path(@user, activity),
                class: 'button',
                method: :delete, data: { confirm: 'Are you sure?' }) %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>
<% end %>

app/views/activities/new.html.erb
<h1>New Activity</h1>
<%= form_for([@user, @activity]) do |f| %>

  <fieldset>
    <div class="row">
      <div class="span3 required">
        <%= f.label :date %>
        <%= f.text_field :date, autofocus: true %>
      </div>
    </div>
    <div class="row">
      <div class="span3">
        <small>(date format: YYYY-MM-DD)</small>
      </div>
    </div>
    <div class="row">
      <div class="span3 required">
        <%= f.label :value %>
        <%= f.text_field :value%>
      </div>
    </div>
    <div class="row">
      <div class="span3 required">
        <%= f.submit %>
        <%= link_to "Cancel", user_activities_path(@user), class: 'button' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/dashboard/index.html.erb
<div style="text-align: center">
  <div class="row">
    <h1 class="span9">
      <div class="hidden-phone"><%= @challenge.name %><br>
        <small><%= @challenge.start_date %> - <%= @challenge.end_date %></small>
      </div>
      <%= challenge_countdown %>
    </h1>
  </div>
  <div class="row">
    <div class="span3 offset3">
      <button class="btn <%= style_challenge %> btn-block" style="height: 70px; font-size: 50px;"><%= @challenge.target %></button>
      <p>Challenge Total</p>
    </div>
  </div>

  <div class="row" style="">
    <div class="span3">
      <button class="btn btn-info btn-block" style="height: 70px; font-size:50px;"><%= @challenge.accumulated_total %></button>
      <p>Team Total</p>
    </div>

    <div class="span3">
      <button class="btn btn-info btn-block" style="height: 70px; font-size: 50px;"><%= @challenge.target_needed_to_date %></button>
      <p>Total needed to date</p>
    </div>

    <div class="span3">
      <button class="btn <%= style_deficit %> btn-block" style="height: 70px; font-size: 50px;"><%= @challenge.deficit %></button>
      <p>Deficit</p>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="span5 offset2">
      <strong>Individual Totals</strong>
      <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>kms</th>
              <th>m</th>
              <th>#</th>
              <th>%</th>
            </tr>
          </thead>
          <tbody>
            <% @challenge.users.each do |user| %>
            <tr>
              <td>
                <%= link_to_if current_user == user, user.preferred_name,
                  user_activities_path(user) %>
                <%= image_tag 'yellow_jersey.png'\
                  if @challenge.highest_kilometers?(user) %>
                <%= image_tag 'spotted_jersey.png'\
                  if @challenge.highest_ascent?(user) %>
                <%= image_tag 'green_jersey.png'\
                  if @challenge.highest_achievements?(user) %></td>
              <td><%= user.total_distance_for(@challenge.period) %></td>
              <td><%= user.total_ascent_for(@challenge.period) %></td>
              <td><%= user.total_achievements_for(@challenge.period) %></td>
              <td><%= user.percent_completed %></td>
            </tr>
          </tbody>
        <%end%>
      </table>
    </div>
  </div>

  <br><br><br>

<!--Modal windows code-->
<!-- <div class="modal hide fade" id="myModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Enter Activity</h3>
  </div>
  <div class="modal-body">
    <p>How many kilometers today?</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn">Close</a>
    <a href="#" class="btn btn-primary">Save changes</a>
  </div>
</div>

<%= link_to 'Launch Modal', '#', class: 'btn', data: {
  toggle: 'modal',
  target: '#myModal'
} %> -->

<!--Hover code-->
<!-- <%= link_to 'Hover Popover', '', class: 'btn', data: {
  toggle: 'popover',
  title: 'This is the title',
  content: 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus.',
  placement: 'bottom'
} %> -->

<!--Tool Tips code
<br />
<div class="row" style="padding-top: 20px">
  <p class="well span5 offset2">Fusce dapibus, <span style="border-bottom:1px dashed #ff0066; cursor:help;" rel="tooltip" title="Tooltip!! Hooray!">tellus</span> ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Nullam id dolor id nibh ultricies vehicula ut id elit. Maecenas sed diam eget risus varius blandit sit amet non magna. Maecenas sed diam eget risus varius blandit sit amet non magna. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Etiam porta sem malesuada magna mollis euismod.</p>
</div>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DMChallenge" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">DMChallenge</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if current_user %>
                  <li><%= link_to "Dashboard", dashboard_path  %></li>
                  <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
              <% end %>
          <!-- <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li> -->
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <!--<div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div>--><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <!-- <a href="http://strava.com/"><%= image_tag 'strava.png' %></a> -->
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section id="errors">
    <header>
      <h2>
        Oops! The <%= object.class.name.humanize.downcase %> could not be saved.
      </h2>
      <h3>
        Please correct the following <%= pluralize(object.errors.count,\
          "error") %>:
      </h3>
    </header>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/welcome/index.html.erb
<%= link_to (image_tag 'facebook_login_button.png'), "/auth/facebook", id: "sign_in" %>
<%= image_tag 'dm.jpg' %>